export const movies = {
  page: 1,
  results: [
    {
      adult: false,
      backdrop_path: "/yDHYTfA3R0jFYba16jBB1ef8oIt.jpg",
      genre_ids: [28, 35, 878],
      id: 533535,
      original_language: "en",
      original_title: "Deadpool \u0026 Wolverine",
      overview:
        "A listless Wade Wilson toils away in civilian life with his days as the morally flexible mercenary, Deadpool, behind him. But when his homeworld faces an existential threat, Wade must reluctantly suit-up again with an even more reluctant Wolverine.",
      popularity: 2433.46,
      poster_path: "/8cdWjvZQUExUUTzyp4t6EDMubfO.jpg",
      release_date: "2024-07-24",
      title: "Deadpool \u0026 Wolverine",
      video: false,
      vote_average: 7.71,
      vote_count: 2804,
    },
    {
      adult: false,
      backdrop_path: "/mKOBdgaEFguADkJhfFslY7TYxIh.jpg",
      genre_ids: [28, 878, 35, 12, 53],
      id: 365177,
      original_language: "en",
      original_title: "Borderlands",
      overview:
        "Returning to her home planet, an infamous bounty hunter forms an unexpected alliance with a team of unlikely heroes. Together, they battle monsters and dangerous bandits to protect a young girl who holds the key to unimaginable power.",
      popularity: 2388.352,
      poster_path: "/865DntZzOdX6rLMd405R0nFkLmL.jpg",
      release_date: "2024-08-07",
      title: "Borderlands",
      video: false,
      vote_average: 5.849,
      vote_count: 450,
    },
    {
      adult: false,
      backdrop_path: "/18wozP6NjPSNBSgCga5bN7yUSzl.jpg",
      genre_ids: [35, 14, 27],
      id: 917496,
      original_language: "en",
      original_title: "Beetlejuice Beetlejuice",
      overview:
        "After a family tragedy, three generations of the Deetz family return home to Winter River. Still haunted by Beetlejuice, Lydia's life is turned upside down when her teenage daughter, Astrid, accidentally opens the portal to the Afterlife.",
      popularity: 1567.733,
      poster_path: "/kKgQzkUCnQmeTPkyIwHly2t6ZFI.jpg",
      release_date: "2024-09-04",
      title: "Beetlejuice Beetlejuice",
      video: false,
      vote_average: 7.159,
      vote_count: 311,
    },
    {
      adult: false,
      backdrop_path: "/stKGOm8UyhuLPR9sZLjs5AkmncA.jpg",
      genre_ids: [16, 10751, 12, 35],
      id: 1022789,
      original_language: "en",
      original_title: "Inside Out 2",
      overview:
        "Teenager Riley's mind headquarters is undergoing a sudden demolition to make room for something entirely unexpected: new Emotions! Joy, Sadness, Anger, Fear and Disgust, who’ve long been running a successful operation by all accounts, aren’t sure how to feel when Anxiety shows up. And it looks like she’s not alone.",
      popularity: 1485.085,
      poster_path: "/vpnVM9B6NMmQpWeZvzLvDESb2QY.jpg",
      release_date: "2024-06-11",
      title: "Inside Out 2",
      video: false,
      vote_average: 7.669,
      vote_count: 3480,
    },
    {
      adult: false,
      backdrop_path: "/lgkPzcOSnTvjeMnuFzozRO5HHw1.jpg",
      genre_ids: [16, 10751, 35, 28],
      id: 519182,
      original_language: "en",
      original_title: "Despicable Me 4",
      overview:
        "Gru and Lucy and their girls—Margo, Edith and Agnes—welcome a new member to the Gru family, Gru Jr., who is intent on tormenting his dad. Gru also faces a new nemesis in Maxime Le Mal and his femme fatale girlfriend Valentina, forcing the family to go on the run.",
      popularity: 1143.062,
      poster_path: "/wWba3TaojhK7NdycRhoQpsG0FaH.jpg",
      release_date: "2024-06-20",
      title: "Despicable Me 4",
      video: false,
      vote_average: 7.192,
      vote_count: 1529,
    },
    {
      adult: false,
      backdrop_path: "/rwakNepsh0dXVcTtWKUVbDsSYYZ.jpg",
      genre_ids: [28, 80, 53, 35],
      id: 573435,
      original_language: "en",
      original_title: "Bad Boys: Ride or Die",
      overview:
        "After their late former Captain is framed, Lowrey and Burnett try to clear his name, only to end up on the run themselves.",
      popularity: 1085.079,
      poster_path: "/oGythE98MYleE6mZlGs5oBGkux1.jpg",
      release_date: "2024-06-05",
      title: "Bad Boys: Ride or Die",
      video: false,
      vote_average: 7.6,
      vote_count: 1878,
    },
    {
      adult: false,
      backdrop_path: "/tCQfubckzzcuCbsGugkpLhfjS5z.jpg",
      genre_ids: [28, 53, 80],
      id: 970347,
      original_language: "en",
      original_title: "The Killer",
      overview:
        'Zee is a feared contract killer known as "the Queen of the Dead," but when she refuses to murder a young blind woman, she finds herself hunted both by criminal colleagues and a determined police detective.',
      popularity: 1084.443,
      poster_path: "/6PCnxKZZIVRanWb710pNpYVkCSw.jpg",
      release_date: "2024-08-22",
      title: "The Killer",
      video: false,
      vote_average: 6.509,
      vote_count: 172,
    },
    {
      adult: false,
      backdrop_path: "/9juRmk8QjcsUcbrevVu5t8VZy5G.jpg",
      genre_ids: [28, 12, 80, 53],
      id: 923667,
      original_language: "cn",
      original_title: "九龍城寨之圍城",
      overview:
        "Set in the 1980s, troubled youth Chan Lok-kwun accidentally enters the Walled City, discovers the order amidst its chaos, and learns important life lessons along the way. In the Walled City, he becomes close friends with Shin, Twelfth Master and AV. Under the leadership of Cyclone, they resist against the invasion of villain Mr. Big in a series of fierce battles. Together, they vow to protect the safe haven that is Kowloon Walled City.",
      popularity: 965.655,
      poster_path: "/PywbVPeIhBFc33QXktnhMaysmL.jpg",
      release_date: "2024-04-23",
      title: "Twilight of the Warriors: Walled In",
      video: false,
      vote_average: 6.737,
      vote_count: 133,
    },
    {
      adult: false,
      backdrop_path: "/yRKyJJYIzfeiVDHBe4LXguPQCvD.jpg",
      genre_ids: [14, 35],
      id: 4011,
      original_language: "en",
      original_title: "Beetlejuice",
      overview:
        "A newly dead New England couple seeks help from a deranged demon exorcist to scare an affluent New York family out of their home.",
      popularity: 941.557,
      poster_path: "/nnl6OWkyPpuMm595hmAxNW3rZFn.jpg",
      release_date: "1988-03-30",
      title: "Beetlejuice",
      video: false,
      vote_average: 7.4,
      vote_count: 6924,
    },
    {
      adult: false,
      backdrop_path: "/tbgIhYwQ5IAgNaFU1SBBxxNXCmm.jpg",
      genre_ids: [80, 28, 53],
      id: 646097,
      original_language: "en",
      original_title: "Rebel Ridge",
      overview:
        "A former Marine confronts corruption in a small town when local law enforcement unjustly seizes the bag of cash he needs to post his cousin's bail.",
      popularity: 831.205,
      poster_path: "/xEt2GSz9z5rSVpIHMiGdtf0czyf.jpg",
      release_date: "2024-08-27",
      title: "Rebel Ridge",
      video: false,
      vote_average: 6.786,
      vote_count: 302,
    },
    {
      adult: false,
      backdrop_path: "/7aPrv2HFssWcOtpig5G3HEVk3uS.jpg",
      genre_ids: [28, 12, 53],
      id: 718821,
      original_language: "en",
      original_title: "Twisters",
      overview:
        "As storm season intensifies, the paths of former storm chaser Kate Carter and reckless social-media superstar Tyler Owens collide when terrifying phenomena never seen before are unleashed. The pair and their competing teams find themselves squarely in the paths of multiple storm systems converging over central Oklahoma in the fight of their lives.",
      popularity: 826.174,
      poster_path: "/pjnD08FlMAIXsfOLKQbvmO0f0MD.jpg",
      release_date: "2024-07-10",
      title: "Twisters",
      video: false,
      vote_average: 6.978,
      vote_count: 1338,
    },
    {
      adult: false,
      backdrop_path: "/9BQqngPfwpeAfK7c2H3cwIFWIVR.jpg",
      genre_ids: [10749, 18],
      id: 1079091,
      original_language: "en",
      original_title: "It Ends with Us",
      overview:
        "When a woman's first love suddenly reenters her life, her relationship with a charming, but abusive neurosurgeon is upended, and she realizes she must learn to rely on her own strength to make an impossible choice for her future.",
      popularity: 693.827,
      poster_path: "/4TzwDWpLmb9bWJjlN3iBUdvgarw.jpg",
      release_date: "2024-08-07",
      title: "It Ends with Us",
      video: false,
      vote_average: 6.74,
      vote_count: 279,
    },
    {
      adult: false,
      backdrop_path: "/4ft6TR9wA6bra0RLL6G7JFDQ5t1.jpg",
      genre_ids: [28, 35],
      id: 704239,
      original_language: "en",
      original_title: "The Union",
      overview:
        "A New Jersey construction worker goes from regular guy to aspiring spy when his long-lost high school sweetheart recruits him for an espionage mission.",
      popularity: 686.638,
      poster_path: "/d9CTnTHip1RbVi2OQbA2LJJQAGI.jpg",
      release_date: "2024-08-15",
      title: "The Union",
      video: false,
      vote_average: 6.242,
      vote_count: 606,
    },
    {
      adult: false,
      backdrop_path: "/9SSEUrSqhljBMzRe4aBTh17rUaC.jpg",
      genre_ids: [27, 878],
      id: 945961,
      original_language: "en",
      original_title: "Alien: Romulus",
      overview:
        "While scavenging the deep ends of a derelict space station, a group of young space colonizers come face to face with the most terrifying life form in the universe.",
      popularity: 684.302,
      poster_path: "/b33nnKl1GSFbao4l3fZDDqsMx0F.jpg",
      release_date: "2024-08-13",
      title: "Alien: Romulus",
      video: false,
      vote_average: 7.1,
      vote_count: 957,
    },
    {
      adult: false,
      backdrop_path: "/p5kpFS0P3lIwzwzHBOULQovNWyj.jpg",
      genre_ids: [80, 53, 27, 9648],
      id: 1032823,
      original_language: "en",
      original_title: "Trap",
      overview:
        "A father and teen daughter attend a pop concert, where they realize they're at the center of a dark and sinister event.",
      popularity: 678.852,
      poster_path: "/jwoaKYVqPgYemFpaANL941EF94R.jpg",
      release_date: "2024-07-31",
      title: "Trap",
      video: false,
      vote_average: 6.513,
      vote_count: 989,
    },
    {
      adult: false,
      backdrop_path: "/x2thJwMJ6oGlhn7UC4vSwHltEw0.jpg",
      genre_ids: [28, 53, 10770],
      id: 1115396,
      original_language: "en",
      original_title: "Hunting Games",
      overview:
        "When a group of ex-military members is hired to retrieve a lost bag of stolen money, their mission becomes more difficult after a lone hunter finds the bag first.",
      popularity: 664.843,
      poster_path: "/xVbEJzdMxIQqpuLgla0hU8qr9mt.jpg",
      release_date: "2023-05-12",
      title: "Hunting Games",
      video: false,
      vote_average: 4.2,
      vote_count: 4,
    },
    {
      adult: false,
      backdrop_path: "/okVLmXL5y18dfN2R4ufMZEGaeCd.jpg",
      genre_ids: [28, 80],
      id: 1160018,
      original_language: "hi",
      original_title: "किल",
      overview:
        "When an army commando finds out his true love is engaged against her will, he boards a New Dehli-bound train in a daring quest to derail the arranged marriage. But when a gang of knife-wielding thieves begin to terrorize innocent passengers on his train, the commando takes them on himself in a death-defying kill-spree to save those around him — turning what should have been a typical commute into an adrenaline-fueled thrill ride.",
      popularity: 660.928,
      poster_path: "/m2zXTuNPkywdYLyWlVyJZW2QOJH.jpg",
      release_date: "2024-07-03",
      title: "Kill",
      video: false,
      vote_average: 6.785,
      vote_count: 128,
    },
    {
      adult: false,
      backdrop_path: "/bxwKC4qAbceMgHU1xCCTBK1eYdn.jpg",
      genre_ids: [28, 53, 80],
      id: 5492,
      original_language: "en",
      original_title: "Gunner",
      overview:
        "While on a camping trip in order to reconnect, war veteran Colonel Lee Gunner must save his two sons from a gang of violent bikers when they're kidnapped after accidentally stumbling upon to a massive drug operation.",
      popularity: 654.465,
      poster_path: "/5wOdd0PqE2hHGQmePdR1HtRNPgI.jpg",
      release_date: "2024-08-16",
      title: "Gunner",
      video: false,
      vote_average: 5.308,
      vote_count: 73,
    },
    {
      adult: false,
      backdrop_path: "/qkEnklEGDFy4TRVhuHFn2DI2BP6.jpg",
      genre_ids: [27, 53],
      id: 930600,
      original_language: "en",
      original_title: "The Deliverance",
      overview:
        "Ebony Jackson, a struggling single mother fighting her personal demons, moves her family into a new home for a fresh start. But when strange occurrences inside the home raise the suspicions of Child Protective Services and threaten to tear the family apart, Ebony soon finds herself locked in a battle for her life and the souls of her children.",
      popularity: 583.467,
      poster_path: "/og1FteMFRInoQnlZeWqEn8XpXHh.jpg",
      release_date: "2024-08-16",
      title: "The Deliverance",
      video: false,
      vote_average: 6.316,
      vote_count: 256,
    },
    {
      adult: false,
      backdrop_path: "/kwzNUM4yZ26XuNAPSyaWwJeWRP4.jpg",
      genre_ids: [28, 35, 14],
      id: 950526,
      original_language: "pt",
      original_title: "O Mestre da Fumaça",
      overview:
        "The journey of Gabriel and Daniel, two brothers cursed by the Chinese mafia with its feared Three Generations Revenge, who have already reaped the life of their grandfather and their father. To survive, one of the brothers must learn the Smoke Style secrets, a little known Cannabis martial art, taught by a single master, high up in the mountains.",
      popularity: 566.672,
      poster_path: "/mg6YkwftQOJjpT2ygYlCi11LWeC.jpg",
      release_date: "2023-05-18",
      title: "The Smoke Master",
      video: false,
      vote_average: 5.15,
      vote_count: 10,
    },
  ],
  total_pages: 20,
  total_results: 200,
};
