export const TrendingMovies = {
   page:1,
   results:[
      {
         "backdrop_path":"/cyKH7pDFlxIXluqRyNoHHEpxSDX.jpg",
         "id":646097,
         "title":"Rebel Ridge",
         "original_title":"Rebel Ridge",
         "overview":"A former Marine confronts corruption in a small town when local law enforcement unjustly seizes the bag of cash he needs to post his cousin's bail.",
         "poster_path":"/xEt2GSz9z5rSVpIHMiGdtf0czyf.jpg",
         "media_type":"movie",
         "adult":false,
         "original_language":"en",
         "genre_ids":[
            80,
            28,
            53
         ],
         "popularity":1723.672,
         "release_date":"2024-08-27",
         "video":false,
         "vote_average":6.995,
         "vote_count":438
      },
      {
         "backdrop_path":"/stKGOm8UyhuLPR9sZLjs5AkmncA.jpg",
         "id":1022789,
         "title":"Inside Out 2",
         "original_title":"Inside Out 2",
         "overview":"Teenager Riley's mind headquarters is undergoing a sudden demolition to make room for something entirely unexpected: new Emotions! Joy, Sadness, Anger, Fear and Disgust, who’ve long been running a successful operation by all accounts, aren’t sure how to feel when Anxiety shows up. And it looks like she’s not alone.",
         "poster_path":"/vpnVM9B6NMmQpWeZvzLvDESb2QY.jpg",
         "media_type":"movie",
         "adult":false,
         "original_language":"en",
         "genre_ids":[
            16,
            10751,
            12,
            35,
            14
         ],
         "popularity":1690.095,
         "release_date":"2024-06-11",
         "video":false,
         "vote_average":7.667,
         "vote_count":3533
      },
      {
         "backdrop_path":"/p5kpFS0P3lIwzwzHBOULQovNWyj.jpg",
         "id":1032823,
         "title":"Trap",
         "original_title":"Trap",
         "overview":"A father and teen daughter attend a pop concert, where they realize they're at the center of a dark and sinister event.",
         "poster_path":"/jwoaKYVqPgYemFpaANL941EF94R.jpg",
         "media_type":"movie",
         "adult":false,
         "original_language":"en",
         "genre_ids":[
            80,
            53
         ],
         "popularity":601.575,
         "release_date":"2024-07-31",
         "video":false,
         "vote_average":6.521,
         "vote_count":1031
      },
      {
         "backdrop_path":"/Asg2UUwipAdE87MxtJy7SQo08XI.jpg",
         "id":957452,
         "title":"The Crow",
         "original_title":"The Crow",
         "overview":"Soulmates Eric and Shelly are brutally murdered when the demons of her dark past catch up with them. Given the chance to save his true love by sacrificing himself, Eric sets out to seek merciless revenge on their killers, traversing the worlds of the living and the dead to put the wrong things right.",
         "poster_path":"/AqchrmqqSCsEvhuinXgFXTD8q83.jpg",
         "media_type":"movie",
         "adult":false,
         "original_language":"en",
         "genre_ids":[
            28,
            14,
            27,
            53
         ],
         "popularity":275.489,
         "release_date":"2024-08-21",
         "video":false,
         "vote_average":5.492,
         "vote_count":184
      },
      {
         "backdrop_path":"/18wozP6NjPSNBSgCga5bN7yUSzl.jpg",
         "id":917496,
         "title":"Beetlejuice Beetlejuice",
         "original_title":"Beetlejuice Beetlejuice",
         "overview":"After a family tragedy, three generations of the Deetz family return home to Winter River. Still haunted by Beetlejuice, Lydia's life is turned upside down when her teenage daughter, Astrid, accidentally opens the portal to the Afterlife.",
         "poster_path":"/kKgQzkUCnQmeTPkyIwHly2t6ZFI.jpg",
         "media_type":"movie",
         "adult":false,
         "original_language":"en",
         "genre_ids":[
            35,
            14,
            27
         ],
         "popularity":1434.036,
         "release_date":"2024-09-04",
         "video":false,
         "vote_average":7.219,
         "vote_count":426
      },
      {
         "backdrop_path":"/waPt1Dv5kWhbNna5rTv2NGfeb7O.jpg",
         "id":533535,
         "title":"Deadpool \u0026 Wolverine",
         "original_title":"Deadpool \u0026 Wolverine",
         "overview":"A listless Wade Wilson toils away in civilian life with his days as the morally flexible mercenary, Deadpool, behind him. But when his homeworld faces an existential threat, Wade must reluctantly suit-up again with an even more reluctant Wolverine.",
         "poster_path":"/8cdWjvZQUExUUTzyp4t6EDMubfO.jpg",
         "media_type":"movie",
         "adult":false,
         "original_language":"en",
         "genre_ids":[
            28,
            35,
            878
         ],
         "popularity":2680.931,
         "release_date":"2024-07-24",
         "video":false,
         "vote_average":7.7,
         "vote_count":2851
      },
      {
         "backdrop_path":"/9SSEUrSqhljBMzRe4aBTh17rUaC.jpg",
         "id":945961,
         "title":"Alien: Romulus",
         "original_title":"Alien: Romulus",
         "overview":"While scavenging the deep ends of a derelict space station, a group of young space colonizers come face to face with the most terrifying life form in the universe.",
         "poster_path":"/b33nnKl1GSFbao4l3fZDDqsMx0F.jpg",
         "media_type":"movie",
         "adult":false,
         "original_language":"en",
         "genre_ids":[
            27,
            878
         ],
         "popularity":686.192,
         "release_date":"2024-08-13",
         "video":false,
         "vote_average":7.102,
         "vote_count":972
      },
      {
         "backdrop_path":"/rbEsJL59iW5mr4s1YnLocEFdO3Q.jpg",
         "id":748167,
         "title":"Uglies",
         "original_title":"Uglies",
         "overview":"In a futuristic dystopia with enforced beauty standards, a teen awaiting mandatory cosmetic surgery embarks on a journey to find her missing friend.",
         "poster_path":"/og1SH6we0UQx5XNIDSfxDD4S1Sp.jpg",
         "media_type":"movie",
         "adult":false,
         "original_language":"en",
         "genre_ids":[
            878,
            18,
            12
         ],
         "popularity":137.788,
         "release_date":"2024-09-12",
         "video":false,
         "vote_average":6.275,
         "vote_count":118
      },
      {
         "backdrop_path":"/6ToGkmqn0KG0UGGGUAC1Ww0e5CM.jpg",
         "id":1226578,
         "title":"Longlegs",
         "original_title":"Longlegs",
         "overview":"FBI Agent Lee Harker is assigned to an unsolved serial killer case that takes an unexpected turn, revealing evidence of the occult. Harker discovers a personal connection to the killer and must stop him before he strikes again.",
         "poster_path":"/5aj8vVGFwGVbQQs26ywhg4Zxk2L.jpg",
         "media_type":"movie",
         "adult":false,
         "original_language":"en",
         "genre_ids":[
            80,
            27,
            53
         ],
         "popularity":583.698,
         "release_date":"2024-05-31",
         "video":false,
         "vote_average":6.718,
         "vote_count":799
      },
      {
         "backdrop_path":"/mKOBdgaEFguADkJhfFslY7TYxIh.jpg",
         "id":365177,
         "title":"Borderlands",
         "original_title":"Borderlands",
         "overview":"Returning to her home planet, an infamous bounty hunter forms an unexpected alliance with a team of unlikely heroes. Together, they battle monsters and dangerous bandits to protect a young girl who holds the key to unimaginable power.",
         "poster_path":"/865DntZzOdX6rLMd405R0nFkLmL.jpg",
         "media_type":"movie",
         "adult":false,
         "original_language":"en",
         "genre_ids":[
            28,
            878,
            35,
            12,
            53
         ],
         "popularity":2231.526,
         "release_date":"2024-08-07",
         "video":false,
         "vote_average":5.868,
         "vote_count":489
      },
      {
         "backdrop_path":"/7aPrv2HFssWcOtpig5G3HEVk3uS.jpg",
         "id":718821,
         "title":"Twisters",
         "original_title":"Twisters",
         "overview":"As storm season intensifies, the paths of former storm chaser Kate Carter and reckless social-media superstar Tyler Owens collide when terrifying phenomena never seen before are unleashed. The pair and their competing teams find themselves squarely in the paths of multiple storm systems converging over central Oklahoma in the fight of their lives.",
         "poster_path":"/pjnD08FlMAIXsfOLKQbvmO0f0MD.jpg",
         "media_type":"movie",
         "adult":false,
         "original_language":"en",
         "genre_ids":[
            28,
            12,
            53
         ],
         "popularity":779.475,
         "release_date":"2024-07-10",
         "video":false,
         "vote_average":6.982,
         "vote_count":1370
      },
      {
         "backdrop_path":"/lgkPzcOSnTvjeMnuFzozRO5HHw1.jpg",
         "id":519182,
         "title":"Despicable Me 4",
         "original_title":"Despicable Me 4",
         "overview":"Gru and Lucy and their girls—Margo, Edith and Agnes—welcome a new member to the Gru family, Gru Jr., who is intent on tormenting his dad. Gru also faces a new nemesis in Maxime Le Mal and his femme fatale girlfriend Valentina, forcing the family to go on the run.",
         "poster_path":"/wWba3TaojhK7NdycRhoQpsG0FaH.jpg",
         "media_type":"movie",
         "adult":false,
         "original_language":"en",
         "genre_ids":[
            16,
            10751,
            35,
            28
         ],
         "popularity":1496.45,
         "release_date":"2024-06-20",
         "video":false,
         "vote_average":7.2,
         "vote_count":1571
      },
      {
         "backdrop_path":"/jnrLpUtOKelKhmGieEBcAvrsrFB.jpg",
         "id":1114513,
         "title":"Speak No Evil",
         "original_title":"Speak No Evil",
         "overview":"When an American family is invited to spend the weekend at the idyllic country estate of a charming British family they befriended on vacation, what begins as a dream holiday soon warps into a snarled psychological nightmare.",
         "poster_path":"/dA4N6uWOnEMgbxXwFX7qX7adzs8.jpg",
         "media_type":"movie",
         "adult":false,
         "original_language":"en",
         "genre_ids":[
            27,
            53
         ],
         "popularity":439.442,
         "release_date":"2024-09-11",
         "video":false,
         "vote_average":7.152,
         "vote_count":56
      },
      {
         "backdrop_path":"/yRKyJJYIzfeiVDHBe4LXguPQCvD.jpg",
         "id":4011,
         "title":"Beetlejuice",
         "original_title":"Beetlejuice",
         "overview":"A newly dead New England couple seeks help from a deranged demon exorcist to scare an affluent New York family out of their home.",
         "poster_path":"/nnl6OWkyPpuMm595hmAxNW3rZFn.jpg",
         "media_type":"movie",
         "adult":false,
         "original_language":"en",
         "genre_ids":[
            14,
            35
         ],
         "popularity":885.063,
         "release_date":"1988-03-30",
         "video":false,
         "vote_average":7.382,
         "vote_count":6989
      },
      {
         "backdrop_path":"/wSZbtiFIK1fkKZdSRtn2kz2Ttfd.jpg",
         "id":1139817,
         "title":"Officer Black Belt",
         "original_title":"무도실무관",
         "overview":"A talented martial artist who can't walk past a person in need unites with a probation officer to fight and prevent crime as a martial arts officer.",
         "poster_path":"/lvlx1pXt1fZYpta1cdQiBfj0fb.jpg",
         "media_type":"movie",
         "adult":false,
         "original_language":"ko",
         "genre_ids":[
            28,
            35,
            80
         ],
         "popularity":85.798,
         "release_date":"2024-09-10",
         "video":false,
         "vote_average":7.7,
         "vote_count":30
      },
      {
         "backdrop_path":"/rwakNepsh0dXVcTtWKUVbDsSYYZ.jpg",
         "id":573435,
         "title":"Bad Boys: Ride or Die",
         "original_title":"Bad Boys: Ride or Die",
         "overview":"After their late former Captain is framed, Lowrey and Burnett try to clear his name, only to end up on the run themselves.",
         "poster_path":"/oGythE98MYleE6mZlGs5oBGkux1.jpg",
         "media_type":"movie",
         "adult":false,
         "original_language":"en",
         "genre_ids":[
            28,
            80,
            53,
            35
         ],
         "popularity":1135.256,
         "release_date":"2024-06-05",
         "video":false,
         "vote_average":7.546,
         "vote_count":1915
      },
      {
         "backdrop_path":"/AmR3JG1VQVxU8TfAvljUhfSFUOx.jpg",
         "id":348,
         "title":"Alien",
         "original_title":"Alien",
         "overview":"During its return to the earth, commercial spaceship Nostromo intercepts a distress signal from a distant planet. When a three-member team of the crew discovers a chamber containing thousands of eggs on the planet, a creature inside one of the eggs attacks an explorer. The entire crew is unaware of the impending nightmare set to descend upon them when the alien parasite planted inside its unfortunate host is birthed.",
         "poster_path":"/vfrQk5IPloGg1v9Rzbh2Eg3VGyM.jpg",
         "media_type":"movie",
         "adult":false,
         "original_language":"en",
         "genre_ids":[
            27,
            878
         ],
         "popularity":237.85,
         "release_date":"1979-05-25",
         "video":false,
         "vote_average":8.154,
         "vote_count":14493
      },
      {
         "backdrop_path":"/tCQfubckzzcuCbsGugkpLhfjS5z.jpg",
         "id":970347,
         "title":"The Killer",
         "original_title":"The Killer",
         "overview":"Zee is a feared contract killer known as \"the Queen of the Dead,\" but when she refuses to murder a young blind woman, she finds herself hunted both by criminal colleagues and a determined police detective.",
         "poster_path":"/6PCnxKZZIVRanWb710pNpYVkCSw.jpg",
         "media_type":"movie",
         "adult":false,
         "original_language":"en",
         "genre_ids":[
            28,
            53,
            80
         ],
         "popularity":903.145,
         "release_date":"2024-08-22",
         "video":false,
         "vote_average":6.518,
         "vote_count":192
      },
      {
         "backdrop_path":"/yNU8UF3DOmv3G9gVNAj34beclTG.jpg",
         "id":698687,
         "title":"Transformers One",
         "original_title":"Transformers One",
         "overview":"The untold origin story of Optimus Prime and Megatron, better known as sworn enemies, but once were friends bonded like brothers who changed the fate of Cybertron forever.",
         "poster_path":"/iHPIBzrjJHbXeY9y7VVbEVNt7LW.jpg",
         "media_type":"movie",
         "adult":false,
         "original_language":"en",
         "genre_ids":[
            16,
            878,
            12,
            28,
            10751
         ],
         "popularity":429.209,
         "release_date":"2024-09-11",
         "video":false,
         "vote_average":8.45,
         "vote_count":10
      },
      {
         "backdrop_path":"/wNAhuOZ3Zf84jCIlrcI6JhgmY5q.jpg",
         "id":786892,
         "title":"Furiosa: A Mad Max Saga",
         "original_title":"Furiosa: A Mad Max Saga",
         "overview":"As the world fell, young Furiosa is snatched from the Green Place of Many Mothers and falls into the hands of a great Biker Horde led by the Warlord Dementus. Sweeping through the Wasteland they come across the Citadel presided over by The Immortan Joe. While the two Tyrants war for dominance, Furiosa must survive many trials as she puts together the means to find her way home.",
         "poster_path":"/iADOJ8Zymht2JPMoy3R7xceZprc.jpg",
         "media_type":"movie",
         "adult":false,
         "original_language":"en",
         "genre_ids":[
            28,
            12,
            878
         ],
         "popularity":424.062,
         "release_date":"2024-05-22",
         "video":false,
         "vote_average":7.577,
         "vote_count":3038
      }
   ],
   "total_pages":1000,
   "total_results":20000
}